# Xpath's
barra_email = '/html/body/form/div/div/div[2]/section[3]/div/input[1]'
click__email = '/html/body/form/div/div/div[2]/section[3]/div/button'
barra_senha = '/html/body/form/div/div/div[2]/section[4]/div/input'
click_senha = '/html/body/form/div/div/div[2]/section[4]/div/button[2]'
click_base = '/html/body/div[1]/div/main/div/div[1]/div[2]/div/div[3]/div/div[2]/div[4]/div/button[2]'
click_vendas = '/html/body/div[2]/div[5]/div[2]/ul/li[2]/a'
click_vendas_nfe = '/html/body/div[2]/header/div[3]/div/ul/li[2]/a'
click_configurar_impostos = '/html/body/div[2]/div[1]/div[2]/form/div/div[2]/div/div[1]/div/ul/li[4]/a/span'
click_mensage_box = '/html/body/div[7]/div/div/div[2]/button[2]'
click_cfop = '/html/body/div[2]/div[7]/div[2]/div[3]/div[3]/div/div[9]/a[10]/span[2]/div/span'
click_barra_cfop = '/html/body/div[2]/div[7]/div[2]/div[3]/div[3]/div/div[1]/div/div/div[2]/table/thead/tr[2]/td[2]/span/input'
click_ncm = '/html/body/div[2]/div[7]/div[2]/div[3]/div[3]/div/div[1]/div/div/div[4]/table/tbody/tr/td[2]'                   
bahia_cfop = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[3]/a[5]/span[2]/div/span/i'
barra_cfop_vdn_rnd = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[2]/span[1]/input'
btn_barra_cfop_vdn_rnd = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[2]/span[1]/span/span'
barra_cfop_qnd_hou_tribut = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[4]/span[1]/input'
btn_barra_cfop_qnd_hou_tribut = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[4]/span[1]/span/span'
barra_cfop_icms = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[3]/span[1]/input'
btn_barra_cfop_icms = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[3]/span[1]/span/span'
barra_cfop_nao_icms = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[5]/span[1]/input' 
btn_barra_cfop_nao_icms = '/html/body/div[2]/div[9]/div[2]/div[3]/div[3]/div/div[1]/div[5]/span[1]/span/span'


